name: Scrape Data

on:
  schedule:
    - cron: "0 1 * * *" # 6:30am IST
  workflow_dispatch:

jobs:
  run-scraper:
    uses: gtech-mulearn/leaderboard/.github/workflows/scraper.yaml@main
    secrets: inherit
    if: github.ref == 'refs/heads/main'
    permissions:
      issues: read
      pull-requests: read
      contents: write
    with:
      slack-eod-channel: ${{ vars.SLACK_EOD_CHANNEL }}
